// Mirrors include/config.h

export const config = {
  SENSOR_SAMPLE_MS: 50,
  TELEMETRY_INTERVAL_MS: 200,
  BLE_SCAN_INTERVAL_MS: 5000,
  FALL_ACCEL_THRESHOLD_G: 2.5,
  IMPACT_THRESHOLD_G: 4.0,
  MIN_PRESSURE_THRESHOLD: 100,
  LOW_BATTERY_PERCENT: 15,
};
